development:
  secret_key_base: 526883819db9549b9cdd7e62e07a385473fb503611a0e5f42673115be670ae4d485bd54c0eb3ad92d1d6ca84d0101cce210cf0955fa20df802c54b92aba836ce
  GOOGLE_CLIENT_ID: 62158956784-42d1m6snm7jvertajr2robceb6ng4ui8.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: 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
  redirect_uri: "http://localhost:3000/auth/callback"
  client_secret: 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
  google_client_secret: "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"
  GOOGLE_CLIENT_SECRET: "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"
production:
  secret_key_base: 526883819db9549b9cdd7e62e07a385473fb503611a0e5f42673115be670ae4d485bd54c0eb3ad92d1d6ca84d0101cce210cf0955fa20df802c54b92aba836ce
  GOOGLE_CLIENT_ID: 62158956784-42d1m6snm7jvertajr2robceb6ng4ui8.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: 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
  redirect_uri: "http://localhost:3000/auth/callback"
  client_secret: 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
  google_client_secret: "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"
  GOOGLE_CLIENT_SECRET: "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"